name: Run Selenium Code Every 15 Minutes

on:
  schedule:
#    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # שלב 1 - משיכת הקוד מה-repo
      - name: Check out repository
        uses: actions/checkout@v2

      # שלב 2 - התקנת Java (כאן 11, אפשר לשנות לגירסה אחרת)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # שלב 3 - התקנת Chrome ו־ChromeDriver
      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          # התקנת Chrome
          sudo apt-get install -y google-chrome-stable
          # התקנת Chromium (לפעמים צריך) ו־ChromeDriver
          sudo apt-get install -y chromium-chromedriver

      # שלב 4 - הידור הפרויקט (Compile)
      - name: Build with Maven
        run: mvn clean install
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TO_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}

      # שלב 5 - הרצת הטסטים עם Selenium ב־Headless
      # אם הקוד שלך כבר יודע לעבוד Headless לא צריך Xvfb,
      # אבל אם אתה משתמש ב-UI מלא, ניתן לעטוף ב-xvfb-run.
      - name: Run tests
        run: mvn test