name: Run Selenium Code Every 15 Minutes

# We allow manual dispatch AND schedule
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository code
      - uses: actions/checkout@v3

      # 2) Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'



      # 3) Check Chrome version
      - name: Check Chrome Version
        run: google-chrome --version

      # 4) Install Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      

      # 5) Verify Chrome installation
      - name: Verify Chrome Installation
        run: google-chrome --version


      # 6) Install matching ChromeDriver
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Detected Chrome version: $CHROME_VERSION"
          echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
      
      
  

      # 4) Build & Run your Maven project
      - name: Build and Run the code
        run: |
          mvn clean install
          mvn exec:java -Dexec.mainClass="org.automation.MayaAlertMonitor"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TO_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}
