name: Run Selenium Code Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TO_WHATSAPP_NUMBER: "whatsapp:+972508266273"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # בוחר את ספק ה־JDK
          java-version: '11'

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver



      - name: Run MayaAlertMonitor
        run: mvn compile exec:java -Dexec.mainClass="org.automation.MayaAlertMonitor"

      - name: Upload Screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png