name: Run Selenium Code Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository code
      - uses: actions/checkout@v3

      # 2) Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3) Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # 4) Verify Chrome installation
      - name: Verify Chrome Installation
        run: google-chrome --version

      # 5) Setup ChromeDriver using pre-built action
      - name: Setup ChromeDriver
        uses: actions/setup-chromedriver@v3
        with:
          version: latest  # Automatically matches the installed Chrome version

      # 6) Build & Run your Maven project
      - name: Build and Run the code
        run: |
          mvn clean install
          mvn exec:java -Dexec.mainClass="org.automation.MayaAlertMonitor"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TO_WHATSAPP_NUMBER: ${{ secrets.TO_WHATSAPP_NUMBER }}
