name: Maya Important Messages

on:
  schedule:
    - cron: '*/15 8-9 * * 0-4'
    - cron: '0 10-16 * * 0-4'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y chromium-chromedriver

      - name: Run MayaAlertMonitor
        run: mvn compile exec:java -Dexec.mainClass="org.automation.MayaAlertMonitor"

      - name: Upload Screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png
